#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
alias la='ls -la'
alias ll='ls -la'
export PATH=/usr/local/Cellar/curl/7.57.0/bin:/usr/local/Cellar/openssl/1.0.**/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:/usr/local/bin:/usr/local/sbin

# setting for node
export PATH=$HOME/.nodebrew/current/bin:$PATH


# setting for php
# export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/bin:$PATH"
export PATH="/usr/local/opt/php@7.1/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/php@7.1/lib"
export CPPFLAGS="-I/usr/local/opt/php@7.1/include"
export PATH=$PATH:$HOME/.composer/vendor/bin

# setting for python
export PYENV_ROOT=~/.pyenv
export PATH="~/.pyenv/shims:$PATH"↲
eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"


# setting for golang
export GOPATH=~/go
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export PORT=5000
export DATABASE_URL=postgres://admin:admin@localhost:5432/demo?sslmode=disable


# setting for rbenv
export PATH="~/.rbenv/shims:$PATH"
eval "$(rbenv init -)"
#rbenv global 2.5.0
 
